#!/usr/bin/env python
"""
Static site generator for TIL Blog
Converts Flask app to static HTML files for deployment
With enhanced debugging for GitHub Actions
"""
import os
import sys
import time
import re
import shutil
from pathlib import Path

def log(message):
    """Print a timestamped log message"""
    print(f"[{time.strftime('%H:%M:%S')}] {message}")
    sys.stdout.flush()  # Ensure logs are immediately visible in GitHub Actions

def ensure_dir(path):
    """Create directory if it doesn't exist"""
    if not path.exists():
        path.mkdir(parents=True)
        log(f"Created directory: {path}")

def main():
    """Main build process with simplified approach for GitHub Actions"""
    log("Starting TIL blog static site generation in debug mode")
    
    # Configuration
    BUILD_DIR = Path("build")
    STATIC_DIR = Path("static") if Path("static").exists() else None
    
    # Clean build directory
    if BUILD_DIR.exists():
        log(f"Removing existing build directory: {BUILD_DIR}")
        shutil.rmtree(BUILD_DIR)
    
    ensure_dir(BUILD_DIR)
    log(f"Created fresh build directory: {BUILD_DIR}")
    
    # Check if we're running in GitHub Actions
    is_github_actions = os.environ.get('GITHUB_ACTIONS') == 'true'
    log(f"Running in GitHub Actions: {is_github_actions}")
    
    # List current directory contents
    log("Current directory contents:")
    for item in os.listdir('.'):
        log(f"  - {item}")
    
    # Check if app.py exists
    if not os.path.exists('app.py'):
        log("ERROR: app.py not found in current directory!")
        return 1
    
    log("Checking environment:")
    log(f"Python version: {sys.version}")
    log(f"Working directory: {os.getcwd()}")
    
    # Create a simple index.html file directly
    log("Creating simple index.html for test deployment")
    with open(BUILD_DIR / "index.html", "w") as f:
        f.write("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TIL Blog - GitHub Pages Deployment Test</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
        }
        h1 { color: #3498db; }
        .note { background: #f8f9fa; padding: 1rem; border-left: 4px solid #3498db; }
    </style>
</head>
<body>
    <h1>TIL Blog - Deployment Test</h1>
    
    <div class="note">
        <p>This is a test page generated by the build script.</p>
        <p>If you're seeing this page, your GitHub Pages setup is working correctly!</p>
    </div>
    
    <h2>Next Steps:</h2>
    <ol>
        <li>Debug your Flask app for use with the build script</li>
        <li>Update the build script to crawl your Flask app</li>
        <li>Deploy your full TIL blog</li>
    </ol>

    <footer>
        <p>Generated on: """ + time.strftime('%Y-%m-%d %H:%M:%S') + """</p>
    </footer>
</body>
</html>""")
    
    log("Created test index.html file")
    
    # Copy static files if they exist
    if STATIC_DIR and STATIC_DIR.exists():
        static_target = BUILD_DIR / STATIC_DIR.name
        if static_target.exists():
            shutil.rmtree(static_target)
        
        shutil.copytree(STATIC_DIR, static_target)
        log(f"Copied static files to {static_target}")
    else:
        log("No static directory found, skipping static files")
    
    # Create .nojekyll file to prevent GitHub Pages from using Jekyll
    with open(BUILD_DIR / ".nojekyll", "w") as f:
        f.write("")
    
    log("Created .nojekyll file")
    log("Static site generation complete!")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())